# Generated by Django 3.1.7 on 2021-03-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('LT', models.CharField(blank=True, max_length=20)),
                ('LB', models.CharField(blank=True, max_length=20)),
                ('property_type', models.CharField(choices=[('RM', 'Rumah'), ('TN', 'Tanah'), ('AP', 'Apartement')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, default='', max_length=20)),
                ('publish_date', models.CharField(blank=True, default='', max_length=20)),
                ('facility', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('JL', 'Jual'), ('SW', 'Sewa')], max_length=2)),
                ('certificate', models.CharField(max_length=20)),
                ('agent', models.ManyToManyField(blank=True, related_name='agent', to='rumah.Agent')),
                ('developer', models.ManyToManyField(blank=True, related_name='developer', to='rumah.Developer')),
                ('source', models.ForeignKey(default='rumah123', on_delete=django.db.models.deletion.CASCADE, to='rumah.source', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.rumah')),
            ],
        ),
    ]
