# Generated by Django 3.1.7 on 2021-03-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='certificate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RumahImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.imagelink')),
                ('rumah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.rumah')),
            ],
        ),
    ]
