# Generated by Django 3.1.7 on 2021-03-08 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0002_auto_20210308_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagelinks', related_query_name='imagelink', to='rumah.rumah'),
        ),
    ]
