# Generated by Django 3.1.7 on 2021-03-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0003_auto_20210308_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RumahImageLink',
        ),
    ]
