# Generated by Django 3.1.7 on 2021-03-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0004_delete_rumahimagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.rumah'),
        ),
    ]
