# Generated by Django 3.1.7 on 2021-03-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0006_auto_20210309_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='developer',
        ),
        migrations.AddField(
            model_name='rumah',
            name='developer',
            field=models.ForeignKey(blank=True, default='-', on_delete=django.db.models.deletion.CASCADE, to='rumah.developer', to_field='name'),
        ),
    ]
