# Generated by Django 3.1.7 on 2021-03-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0008_auto_20210309_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.rumah'),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='property_name',
            field=models.CharField(max_length=50),
        ),
    ]
