# Generated by Django 3.1.7 on 2021-04-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0011_auto_20210310_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rumah',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='rumah',
            name='certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
