# Generated by Django 3.1.7 on 2021-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah', '0012_auto_20210405_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='property_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='publish_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
